version: '3'

services:
  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    environment:
      - HF_MODEL_ID=BAAI/bge-large-zh
    deploy:
      resources:
        limits:
          memory: 4G  # 根据您的需求调整内存限制

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - embeddings

networks:
  default:
    driver: bridge